/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/_tool'
import { Route as ToolIndexRouteImport } from './routes/_tool.index'
import { Route as ToolCollectionRouteImport } from './routes/_tool.collection'
import { Route as ToolHistoryRouteImport } from './routes/_tool.history'
import { Route as ToolRecordsRouteImport } from './routes/_tool.records'
import { Route as ChartsIndexRouteImport } from './routes/charts.index'
import { Route as ChartsIdRouteImport } from './routes/charts.$id'

const ToolRoute = ToolRouteImport.update({
  id: '/_tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolIndexRoute = ToolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolRoute,
} as any)
const ToolCollectionRoute = ToolCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => ToolRoute,
} as any)
const ToolHistoryRoute = ToolHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ToolRoute,
} as any)
const ToolRecordsRoute = ToolRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => ToolRoute,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIdRoute = ChartsIdRouteImport.update({
  id: '/charts/$id',
  path: '/charts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ToolIndexRoute
  '/collection': typeof ToolCollectionRoute
  '/history': typeof ToolHistoryRoute
  '/records': typeof ToolRecordsRoute
  '/charts/$id': typeof ChartsIdRoute
  '/charts/': typeof ChartsIndexRoute
}
export interface FileRoutesByTo {
  '/collection': typeof ToolCollectionRoute
  '/history': typeof ToolHistoryRoute
  '/records': typeof ToolRecordsRoute
  '/charts/$id': typeof ChartsIdRoute
  '/': typeof ToolIndexRoute
  '/charts': typeof ChartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tool': typeof ToolRouteWithChildren
  '/_tool/collection': typeof ToolCollectionRoute
  '/_tool/history': typeof ToolHistoryRoute
  '/_tool/records': typeof ToolRecordsRoute
  '/charts/$id': typeof ChartsIdRoute
  '/_tool/': typeof ToolIndexRoute
  '/charts/': typeof ChartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/collection' | '/history' | '/records' | '/charts/$id' | '/charts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/collection' | '/history' | '/records' | '/charts/$id' | '/' | '/charts'
  id:
    | '__root__'
    | '/_tool'
    | '/_tool/collection'
    | '/_tool/history'
    | '/_tool/records'
    | '/charts/$id'
    | '/_tool/'
    | '/charts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ToolRoute: typeof ToolRouteWithChildren
  ChartsIdRoute: typeof ChartsIdRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tool': {
      id: '/_tool'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/': {
      id: '/_tool/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ToolIndexRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/collection': {
      id: '/_tool/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof ToolCollectionRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/history': {
      id: '/_tool/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ToolHistoryRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/records': {
      id: '/_tool/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof ToolRecordsRouteImport
      parentRoute: typeof ToolRoute
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$id': {
      id: '/charts/$id'
      path: '/charts/$id'
      fullPath: '/charts/$id'
      preLoaderRoute: typeof ChartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolRouteChildren {
  ToolCollectionRoute: typeof ToolCollectionRoute
  ToolHistoryRoute: typeof ToolHistoryRoute
  ToolRecordsRoute: typeof ToolRecordsRoute
  ToolIndexRoute: typeof ToolIndexRoute
}

const ToolRouteChildren: ToolRouteChildren = {
  ToolCollectionRoute: ToolCollectionRoute,
  ToolHistoryRoute: ToolHistoryRoute,
  ToolRecordsRoute: ToolRecordsRoute,
  ToolIndexRoute: ToolIndexRoute,
}

const ToolRouteWithChildren = ToolRoute._addFileChildren(ToolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ToolRoute: ToolRouteWithChildren,
  ChartsIdRoute: ChartsIdRoute,
  ChartsIndexRoute: ChartsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
